Lab_18/Django/1.11.12/driver/django-chat-app-master/Chat_System/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from chat_app.views import AuthView, MessengerView, RestAPIView
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    url(r'^$', AuthView.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^messenger/$', MessengerView.index),
    url(r'^login/$', login, {'template_name':'chat_app/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name':'chat_app/logout.html'}, name='logout'),
    url(r'^signup/$', AuthView.signup, name='signup'),

    url(r'^api/users_list/$', RestAPIView.UsersList.as_view(), name='users_list'),
    url(r'^api/msgs_logs/$', RestAPIView.MessagesList.as_view(), name='msgs_logs'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

Lab_18/Django/1.11.12/driver/django-livechat-develop/livechat/urls.py
from django.conf.urls.defaults import patterns, url
from livechat.views import LiveChatDetailView, LiveChatArchiveView

urlpatterns = patterns(
    '',
    url(r'^livechat/archive/$',
        LiveChatArchiveView.as_view(),
        name='show_archived_livechat'),
    url(r'^livechat/(?P<slug>[\w-]+)/$',
        LiveChatDetailView.as_view(),
        name='show_livechat'),

)

Lab_18/Django/1.11.12/driver/django-private-chat-dev/example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # This might be reduntant, check later
    url(r'', include('django_private_chat.urls')),
    url(r'', include('custom_app.urls'))
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

Lab_18/Django/1.11.12/driver/driver/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

Lab_18/Django/1.11.12/driver/django-livechat-develop/livechat/models.py
from datetime import datetime, timedelta

from django.conf import settings
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib import comments

from jmbo.managers import PermittedManager
from jmbo.models import ModelBase


Comment = comments.get_model()


class LiveChatManager(PermittedManager):
    """ Model manager for live chat models. Used to find any upcoming live
        chats.
    """

    def upcoming_live_chat(self):
        """
        Find any upcoming or current live chat to advertise on the home page or
        live chat page.
        These are LiveChat's with primary category of 'ask-mama' and category
        of 'live-chat'. The Chat date must be less than 5 days away, or
        happening now.
        """
        chat = None
        now = datetime.now()


        lcqs = self.get_query_set()
        lcqs = lcqs.filter(
            chat_ends_at__gte=now).order_by('-chat_starts_at')
        try:
            if settings.LIVECHAT_PRIMARY_CATEGORY:
                lcqs = lcqs.filter(
                    primary_category__slug=settings.LIVECHAT_PRIMARY_CATEGORY)
        except AttributeError:
            pass
        try:
            if settings.LIVECHAT_CATEGORIES:
                lcqs = lcqs.filter(
                    categories__slug__in=settings.LIVECHAT_CATEGORIES)
        except AttributeError:
            pass
        if lcqs.exists():
            chat = lcqs.latest('chat_starts_at')

        return chat

    def get_current_live_chat(self):
        """ Check if there is a live chat on the go, so that we should take
            over the AskMAMA page with the live chat.
        """
        now = datetime.now()
        chat = self.upcoming_live_chat()
        if chat and chat.is_in_progress():
            return chat
        return None

    def get_last_live_chat(self):
        """ Check if there is a live chat that ended in the last 3 days, and
            return it. We will display a link to it on the articles page.
        """
        now = datetime.now()

        lcqs = self.get_query_set()
        lcqs = lcqs.filter(
            chat_ends_at__lte=now,
            ).order_by('-chat_ends_at')
        for itm in lcqs:
            if itm.chat_ends_at + timedelta(days=3) > now:
                return itm
        return None


class LiveChat(ModelBase):
    """ Defines a live chat model that acts as anchor for a livechat session.
    Participants use Django comments to post questions and comments. An expert
    or moderator can use functionality in the admin site to add responses.

    The live chat can be uses as a stand-alone object instance, or use a
    generic foreign key mechanism to attach to another content type in the
    Django site.

    Template tags are provided to display the chat in place in the site.
    """
    # Use a generic foreign key mechanism to be able to link livechats to any
    # content type.
    # content_type = already exists in ModelBase
    object_id = models.PositiveIntegerField(
        null=True, blank=True,
        editable=False)
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    chat_starts_at = models.DateTimeField(
        help_text="Date and time on which the chat will open for questions.")
    chat_ends_at = models.DateTimeField(
        blank=True,
        help_text="Date and time on which the chat will close.")

    expert = models.CharField(
        help_text="Name, Surname eg. Dr Faith Evans",
        null=False, blank=True, max_length=50
    )

    maximum_questions = models.PositiveIntegerField(
        null=True, blank=True,
        help_text="Please remember to add a slight buffer to allow the maximum number of questions to account for /"
                  "any questions that need to be moderated"
    )

    is_cancelled = models.BooleanField(
        default=False,
        help_text="Indicating whether or not the live chat has been cancelled"
    )

    is_archived = models.BooleanField(
        default=False,
        help_text="Indicating whether or not the live chat has been archived"
    )
    objects = models.Manager()
    chat_finder = LiveChatManager()

    class Meta:
        ordering = ['-chat_starts_at', '-created']
        verbose_name = 'Live Chat'
        verbose_name_plural = 'Live Chats'

    def __unicode__(self):
        return 'Live Chat %s' % (self.title,)

    def comment_set(self):
        """ Get the comments that have been submitted for the chat
        """
        ct = ContentType.objects.get_for_model(self.__class__)
        qs = Comment.objects.filter(
            content_type=ct,
            object_pk=self.pk)
        qs = qs.exclude(is_removed=True)
        qs = qs.order_by('-submit_date')
        return qs

    def check_max_comments(self):
        if self.maximum_questions is not None:
            if self.comment_set().count() >= int(self.maximum_questions)-1:
                self.comments_closed = True
                self.save()


    def is_in_progress(self):
        """ Check if the chat is currently in progress
        """
        now = datetime.now()
        return now > self.chat_starts_at


class LiveChatResponse(models.Model):
    """ This is a response to a live chat comment or question. This response is
    created in the admin site by an expert or moderator.
    """
    livechat = models.ForeignKey(LiveChat)
    author = models.ForeignKey('auth.User')
    comment = models.ForeignKey(Comment)
    response = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def __unicode__(self):
        return "Live Chat Response from %s: %s" % (self.author,
                                                   self.response[:50])

Lab_18/Django/1.11.12/driver/django-livechat-develop/livechat/views.py
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator

from livechat.models import LiveChat


class LiveChatDetailView(TemplateView):
    template_name = 'livechat/show.html'


class LiveChatArchiveView(DetailView):
    template_name = 'livechat/archived_chat.html'

    def get_context_data(self, **kwargs):
        context = super(LiveChatArchiveView, self).get_context_data(**kwargs)
        livechats = LiveChat.objects.all().order_by('-chat_ends_at')

        request = self.request
        try:
            paginator = Paginator(
                livechats,
                per_page=1)
            context['livechats'] = paginator.page(request.GET.get('p', 1))
        except (KeyError, AttributeError):
            pass
        return context

    def get_object(self):
        return LiveChat.objects.filter(is_cancelled=False)

Lab_18/Django/1.11.12/driver/django-livechat-develop/livechat/templates/livechat/archived_chat.html
{% extends "base.html" %}

{% load jmbo_inclusion_tags jmbo_template_tags %}
{% load comments likes_inclusion_tags moderator_inclusion_tags %}
{% load livechat_tags mama_inclusion_tags %}

{% block content %}

<div class="text_banner maroon">
  <div class="h1">LIVE CHAT ARCHIVE</div>
    <div class="items">
      {% if livechats %}
        {% for livechat in livechats.object_list %}
            <div class="banner_content live_chat">
            <div>
            <strong>{{ livechat.title }}<br/></strong>
            {{ livechat.expert }}<br/>
            {{ livechat.chat_starts_at.time }} on {{ livechat.chat_starts_at.date }}<br/>
            </div>
            </div>
            {% for comment in livechat.comment_set %}
            {% if comment.livechatresponse_set.exists %}
            <div class="item comment no-pic">
              <div class="meta">

                <b>{{ comment.name }}</b> asked at {{ comment.submit_date.time }}
                <div class="stamp">{{ comment.comment|linebreaks }}</div>
              </div>

              <div class="item comment" style="background-color: rgb(244, 229, 234)">
                  {% for response in comment.livechatresponse_set.all %}
                      <div class="meta">
                        <b>{{ response.author.first_name }} {{ response.author.last_name }}</b>
                        replied to
                        <b>{{ comment.name }}</b> at {{ response.updated_at.time }}
                        <div class="stamp">{{ response.response }}</div>
                      </div>

                  {% endfor %}
              </div>
              {% endif %}
             {% endfor %}
            </div>
        {% endfor %}

        <div class="pagination">
          {% if livechats.has_previous %}
              <span><a href="?p={{livechats.previous_page_number}}&amp;answered={{answered}}&amp;popular={{popular}}">Previous</a></span> |
          {% else %}
              <span>Previous</span> |
          {% endif %}
          <span class="current">
              Page {{ livechats.number }} of {{ livechats.paginator.num_pages }}
          </span>
          {% if livechats.has_next %}
              | <span><a href="?p={{livechats.next_page_number}}&amp;answered={{answered}}&amp;popular={{popular}}">Next</a></span>
          {% else %}
              | <span>Next</span>
          {% endif %}
        </div>
      {% else %}
        <div class="post">
          No questions yet. Go ahead and ask a question.
        </div>
      {% endif %}
    </div>

  </div>
</div>
{% endblock %}

Lab_18/Django/1.11.12/driver/django-livechat-develop/livechat/templates/livechat/embed.html
{% load jmbo_inclusion_tags jmbo_template_tags %}
{% load comments likes_inclusion_tags %}

<div class="maroon">
  <div class="h1">
    {{livechat.title}}
    <div class="stamp">
        {% humanize_time_diff livechat.created "Ago" %} // <a href="#comments">{{ livechat.comment_count }} Comments</a> // {% likes livechat %}
    </div>
  </div>

  <div class="content-inner">
    <div class="post">
      {{ livechat.description|safe }}
    </div>

    {% object_comments livechat %}

  </div>
</div>

Lab_18/Django/1.11.12/driver/django-livechat-develop/livechat/templates/livechat/index.html
{% extends "base.html" %}

Lab_18/Django/1.11.12/driver/django-livechat-develop/livechat/templates/livechat/show.html
{% extends "base.html" %}

{% load livechat_tags %}

{% block above_content %}
{{ block.super }}
{% endblock %}

{% block content %}
{% show_live_chat %}
{% endblock %}